/// Flutter icons CustomIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData pen =
      IconData(0xf304, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice =
      IconData(0xf522, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_five =
      IconData(0xf523, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_four =
      IconData(0xf524, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_one =
      IconData(0xf525, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_six =
      IconData(0xf526, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_three =
      IconData(0xf527, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_two =
      IconData(0xf528, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamonds =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clubs =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spades =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hearts =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
